title: Orhorhamreru Moronke # your name (or website title) here
logo: "/Moronkegithub.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist 
  <br><br>
  SQL and Python Expert
  <br><br>
  <a href="https://www.linkedin.com/in/moronke-orhorhamreru-04279317a">View My LinkedIn Profile</a> 
  theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
